# docker-compose file syntax version
version: '3.8'

services:
  matchub-db-postgres:
    build:
      # Indicates where to start the directory analysis to find dockerfile, env_file and volumes
      context: .
      dockerfile: docker/dockerfiles/Dockerfile.database
    image: matchub-db-postgres-image
    container_name: matchub-db-postgres-container
    networks:
      - matchub-network
    ports:
      - "5432:5432"
    env_file:
      - docker/secrets/secrets-env-db.env
    volumes:
      - volume-db:/var/lib/postgresql/data

  matchub-api-spring:
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile.api
    image: matchub-api-spring-image
    container_name: matchub-api-spring-container
    networks:
      - matchub-network
    ports:
      - "8080:8080"
    env_file:
      - docker/secrets/secrets-env-api.env
    volumes:
      - volume-api:/openjdk/logs
    depends_on:
      - matchub-db-postgres

  matchub-web-angular:
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile.web
    image: matchub-web-angular-image
    container_name: matchub-web-angular-container
    networks:
      - matchub-network
    ports:
      - "80:80"
    volumes:
      - volume-web:/var/log/nginx
    depends_on:
      - matchub-api-spring

networks:
  matchub-network:
    driver: bridge

volumes:
  volume-db:
    driver: local
  volume-api:
    driver: local
  volume-web:
    driver: local