# docker-compose file syntax version
version: '3.8'

services:
  matchub-db-postgres:
    build:
      # Indicates where to start the directory analysis to find dockerfile, env_file and volumes
      context: .
      dockerfile: matchub-api/docker/database/Dockerfile.database
    image: matchub-db-postgres-image
    container_name: matchub-db-postgres-container
    networks:
      - matchub-network
    ports:
      - "5432:5432"
    env_file:
      - matchub-api/docker/database/secrets-env.env
    volumes:
      - /matchub-api/docker/database/data:/var/lib/postgresql/data

  matchub-api-spring:
    build:
      context: .
      dockerfile: matchub-api/docker/api/Dockerfile.api
    image: matchub-api-spring-image
    container_name: matchub-api-spring-container
    networks:
      - matchub-network
    ports:
      - "8080:8080"
    env_file:
      - matchub-api/docker/api/secrets-env.env
    volumes:
      - /matchub-api/docker/api/data/logs:/app/logs
    depends_on:
      - matchub-db-postgres

  matchub-web-angular:
    build:
      context: .
      dockerfile: matchub-web/docker/Dockerfile.web
    image: matchub-web-angular-image
    container_name: matchub-web-angular-container
    networks:
      - matchub-network
    ports:
      - "80:80"
    volumes:
      - /matchub-web/docker/data/logs:/var/log/nginx
    depends_on:
      - matchub-api-spring

networks:
  matchub-network:
    driver: bridge